---
- name: installing and launching metricbeat
  hosts: webservers
  become: yes
  tasks:

  - name: download metric DEB
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

  - name: install metric DEB
    command: dpkg -i metricbeat-7.4.0-amd64.deb

  - name: drop in metricbeat.yml
    copy:
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml
      
  - name: enable and configure system module
    command: metricbeat modules enable docker

  - name: enable metricbeat setup
    command: metricbeat setup

  - name: metricbeat e command
    command: service metricbeat start 

  - name: enable metricbeat on startup
    systemd:
       name: metricbeat
       enabled: yes
